name: Run semantic release

on:
  workflow_call:
    secrets:
      semantic_release_token:
        description: 'GitHub token for semantic release'
        required: true
    inputs:
      git_user_name:
        description: 'Git user name for semantic release commits'
        required: false
        type: string
      git_user_email:
        description: 'Git user email for semantic release commits'
        required: false
        type: string
      environment:
        description: 'Environment to release'
        required: true
        type: string

env:
  HUSKY: 0
  GITHUB_TOKEN: ${{ secrets.semantic_release_token }}
  GIT_AUTHOR_NAME: ${{ inputs.git_user_name }}
  GIT_AUTHOR_EMAIL: ${{ inputs.git_user_email }}
  GIT_COMMITTER_NAME: ${{ inputs.git_user_name }}
  GIT_COMMITTER_EMAIL: ${{ inputs.git_user_email }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: 'Setup node with cache'
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 24.2.3
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            @semantic-release/github@11.0.2
