name: MAVERICKS CD (Production)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  code-checks:
    name: Run code quality tools
    uses: ./.github/workflows/_code_checks.yaml

  release:
    name: Create Production Release
    needs: [code-checks]
    uses: ./.github/workflows/_sem_release.yaml
    permissions:
      contents: write
      issues: write
      pull-requests: write
    with:
      environment: Production
      git_user_name: JoboxTech
      git_user_email: tech@jobox.ai
    secrets:
      semantic_release_token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

  sync-develop:
    name: Sync master into develop
    needs: [release]
    uses: ./.github/workflows/_sync_branch.yaml
    with:
      source_branch: master
      destination_branch: develop
